### PR TITLE
Legal form & Code Pattern

### PR DESCRIPTION
**Pull request by yil532**

### CODE REVIEW

**Comment by yil532** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/CODAIT/watson-studio-gallery-debater-sentiment-composition-lexicons-project/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yil532** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/CODAIT/watson-studio-gallery-debater-sentiment-composition-lexicons-project/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yil532** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/CODAIT/watson-studio-gallery-debater-sentiment-composition-lexicons-project/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yil532** [comment]
<p>Done.</p>

---

 <a href='https://app.reviewnb.com/CODAIT/watson-studio-gallery-debater-sentiment-composition-lexicons-project/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yil532** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/CODAIT/watson-studio-gallery-debater-sentiment-composition-lexicons-project/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yil532** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/CODAIT/watson-studio-gallery-debater-sentiment-composition-lexicons-project/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by yil532** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/CODAIT/watson-studio-gallery-debater-sentiment-composition-lexicons-project/pull/1/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by tlzhu19 — APPROVED** [review]

**Pull request merged**
